variables:
  VERSION: ${CI_COMMIT_SHORT_SHA}
  APP_NS: moyu
  APP_NAME: ai-moyu-web

stages:
  - build
  - deploy

default:
  tags:
    - docker

before_script:
  - echo "Build on $CI_COMMIT_REF_NAME"
  - ENV=$CI_COMMIT_REF_NAME
  - DOMAIN=ai.moyu.$ENV.openviewtech.com #域名和环境相关
  - POD_COUNT=1 #开发环境、测试环境，只保留一个节点
  - if [[ "$CI_COMMIT_REF_NAME" == "master" ]]; then
  - ENV="prod"
  - DOMAIN=ai.moyu.chat #生成环境的域名单独指定
  - POD_COUNT=2 #生产环境，保留2个节点
  - fi
  - NS="$APP_NS-$ENV"

build:
  stage: build
  image: registry.cn-hangzhou.aliyuncs.com/openviewtech/docker:19.03.12
  only:
    - dev
    - test
    - master
  script:
    - echo "172.19.75.65 gitlab.openviewtech.com" >> /etc/hosts
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - DOCKER_BUILDKIT=1 docker build -t ${CI_REGISTRY_IMAGE}:${ENV}-${VERSION} -t ${CI_REGISTRY_IMAGE}:${ENV}-latest --build-arg ENVIRONMENT=${ENV} .
    - docker push  ${CI_REGISTRY_IMAGE}:${ENV}-${VERSION}
    - docker push  ${CI_REGISTRY_IMAGE}:${ENV}-latest

deploy:
  stage: deploy
  dependencies:
    - build
  image:
    name: registry.cn-hangzhou.aliyuncs.com/openviewtech/kubectl:1.23
    entrypoint: ['']
  only:
    - test
    - dev
  script:
    - mkdir -p $HOME/.kube
    - cp $KUBE_CONFIG $HOME/.kube/config
    - sed -i "s/__POD_COUNT__/$POD_COUNT/" k8s/k8s.yaml
    - sed -i "s/__ENV__/$ENV/" k8s/k8s.yaml
    - sed -i "s/__NS__/$NS/" k8s/k8s.yaml
    - sed -i "s#__HOST__#$DOMAIN#" k8s/k8s.yaml
    - sed -i "s#__APP_IMAGE__#$CI_REGISTRY_IMAGE:$ENV-$VERSION#" k8s/k8s.yaml
    - sed -i "s#__APP_NAME__#$APP_NAME#" k8s/k8s.yaml
    - kubectl apply -f k8s/k8s.yaml
    - kubectl rollout status deployment $APP_NAME -n $NS
    - pods=`kubectl get pods -l app=$APP_NAME -n $NS -o custom-columns=NAME:.metadata.name --no-headers --sort-by=.metadata.creationTimestamp`
    - pods=(`echo $pods|tr "\n" " "`)
    - lastIndex=$((${#pods[@]}-1))
    - pod=${pods[lastIndex]}
    - echo "use $NS/$pod:/opt/www"
    - cd /tmp
    - kubectl cp $NS/$pod:/opt/www www
    - pods=`kubectl get pods -l app=back-server -n $NS -o custom-columns=NAME:.metadata.name --no-headers`
    - pods=(`echo $pods|tr "\n" " "`)
    - pod=${pods[0]}
    - echo "use pod:$pod"
    - cd www
    - tar cf - . |kubectl exec -i -n $NS $pod -- tar xf - -C /opt/www/

master_deploy:
  stage: deploy
  when: manual # 生产环境手动发布
  only:
    - master
  extends: deploy
